language: c
sudo: false
env:
  - PROD=1 TEST_VERBOSE=1
compiler:
  - gcc
  - clang
before_install:
  - mkdir build
  - git clone https://github.com/CBL-ORION/ITK-builds.git external/ITK
  # path for CMake to search for built ITK
  - export ITK_DIR="`( cd external/ITK/usr/local/lib/cmake/ITK-4.9 && pwd )`"
install:
  - mkdir external; git clone https://github.com/CBL-ORION/liborion3mat-mcr-minimal.git external/liborion3mat-mcr-minimal
  - mkdir external; git clone https://github.com/CBL-ORION/liborion3mat-deploy.git external/liborion3mat
  - git clone https://github.com/CBL-ORION/test-data.git test-data
  - ./tool/external/c-tap-harness/download && ./tool/external/c-tap-harness/build
script:
  # version of gcc on Travis-CI does not support ASAN flag
  - if [ "$CC" = "clang" ]; then export CXX="clang++"; fi
  - if [ "$CC" = "gcc" ]; then export BUILD_ENABLE_ASAN=0; else export BUILD_ENABLE_ASAN=1; fi
  - make && make test
branches:
  except:
    - /^wip\//
    - /^blocked/
