#ifndef SEGMENTATION_DEF_H
#define SEGMENTATION_DEF_H 1


#define ORION_LAPLACIAN_APPROX_CONSTANT0 0.5913
#define ORION_LAPLACIAN_APPROX_CONSTANT1 0.66

#define ORION_HDAF_TAYLOR_APPROX_DEGREE 60


#endif /* SEGMENTATION_DEF_H */
