vaa3d-plugin-orion-matlab: ${VAA3D_ORION_MATLAB_LIB_OBJ}

$(VAA3D_ORION_MATLAB_LIB_OBJ): \
		${VAA3D_ORION_MATLAB_LIB_SRC_PATH}/orion_matlab_plugin.cpp \
		${ORION3MAT_LIB_OBJ}
	mkdir -p $(VAA3D_ORION_MATLAB_LIB_BUILD_PATH)
	qmake  -makefile \
		-o $(VAA3D_ORION_MATLAB_LIB_BUILD_PATH)/Makefile \
		VAA3DPATH=${FULL_VAA3D_PATH} \
		$(VAA3D_ORION_MATLAB_LIB_SRC_PATH)/orion_matlab.pro
	$(MAKE) -C$(VAA3D_ORION_MATLAB_LIB_BUILD_PATH)
